import type { Metadata } from "next";
import "./globals.css";
import { Header } from '@/components/shared/header'
import { geistMono, geistSans, montserrat, openSans } from "./fonts/fonts";


export const metadata: Metadata = {
  title: "cocoon salon",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/cocoon-logo.svg", // Or .png, .svg
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable}  ${openSans.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
